# This script is 100% vibecoded, don't trust what you see here, its not meant to be maintainable, it was meant to be quick
"""Reading and writing the .bin and .c output files.

.bin format (all little-endian), declared in music_track.h for C projects:

    MusicTrackHeader:
        uint32 magic       "NOT1"
        uint32 version     format version
        uint32 noteCount   number of NoteEntry entries
        uint32 dataSize    noteCount * sizeof(NoteEntry)
    NoteEntry[noteCount]:
        uint16 frequency_hz  (0 = pause)
        uint16 duration_ms

A whole file maps onto the MusicTrack struct in music_track.h. Files without
the header (the tool's pre-header format) are still accepted by load_bin()
as raw NoteEntry pairs.
"""

import os
import re
import struct

from .constants import NOTE_ASSET_MAGIC, NOTE_ASSET_VERSION

_HEADER_STRUCT = struct.Struct("<4sIII")
_NOTE_SIZE = 4


def save_bin(sequence, bin_path):
    flat = [value for pair in sequence for value in pair]
    data = struct.pack(f"<{len(flat)}H", *flat)
    header = _HEADER_STRUCT.pack(
        NOTE_ASSET_MAGIC, NOTE_ASSET_VERSION, len(sequence), len(data)
    )
    with open(bin_path, "wb") as f:
        f.write(header + data)


def load_bin(bin_path):
    with open(bin_path, "rb") as f:
        raw = f.read()
    if raw[: len(NOTE_ASSET_MAGIC)] == NOTE_ASSET_MAGIC:
        magic, version, note_count, data_size = _HEADER_STRUCT.unpack(
            raw[: _HEADER_STRUCT.size]
        )
        if version != NOTE_ASSET_VERSION:
            raise ValueError(
                f"{bin_path} has unsupported version {version}"
                f" (expected {NOTE_ASSET_VERSION})"
            )
        payload = raw[_HEADER_STRUCT.size :]
        if (
            magic != NOTE_ASSET_MAGIC
            or data_size != note_count * _NOTE_SIZE
            or len(payload) != data_size
        ):
            raise ValueError(f"{bin_path} has an inconsistent MusicTrackHeader")
    else:
        # legacy file without a header: raw pairs only
        payload = raw
        if len(payload) % _NOTE_SIZE != 0:
            raise ValueError(f"{bin_path} size is not a multiple of 4 bytes")
    values = struct.unpack(f"<{len(payload) // 2}H", payload)
    return [(values[i], values[i + 1]) for i in range(0, len(values), 2)]


def save_c_file(sequence, c_path, name, name_of):
    """Write a C asset (header struct + notes array); name_of(freq) labels entries."""
    macro = re.sub(r"\W", "_", name).upper()
    array = re.sub(r"\W", "_", name).lower()
    with open(c_path, "w") as f:
        f.write("// Generated by music_creator.py - do not edit manually\n")
        f.write('#include "music_track.h"\n\n')
        f.write(f"#define {macro}_NOTES_NUMBER {len(sequence)}U\n\n")
        f.write(f"const MusicTrackHeader {array}_music_header = {{\n")
        f.write("    .magic = NOTE_ASSET_MAGIC,\n")
        f.write("    .version = NOTE_ASSET_VERSION,\n")
        f.write(f"    .noteCount = {macro}_NOTES_NUMBER,\n")
        f.write(f"    .dataSize = {macro}_NOTES_NUMBER * sizeof(NoteEntry),\n")
        f.write("};\n\n")
        f.write(f"const uint16_t {array}_music[{macro}_NOTES_NUMBER * 2U] = {{\n")
        for freq, dur in sequence:
            f.write(f"    {freq}U, {dur}U, // {name_of(freq)}\n")
        f.write("};\n")


def list_bin_names(directory):
    """Base names (no extension) of all .bin files in a directory."""
    if not os.path.isdir(directory):
        return []
    return sorted(
        os.path.splitext(f)[0] for f in os.listdir(directory) if f.endswith(".bin")
    )
