# This script is 100% vibecoded, don't trust what you see here, its not meant to be maintainable, it was meant to be quick
"""Reading and writing the .bin and .c output files.

.bin format: little-endian uint16 pairs, 4 bytes per entry:
    frequency_hz, duration_ms, frequency_hz, duration_ms, ...
This matches what buzzerPlay() consumes and doubles as the editor's
save-state format.
"""

import os
import re
import struct


def save_bin(sequence, bin_path):
    flat = [value for pair in sequence for value in pair]
    with open(bin_path, "wb") as f:
        f.write(struct.pack(f"<{len(flat)}H", *flat))


def load_bin(bin_path):
    with open(bin_path, "rb") as f:
        raw = f.read()
    if len(raw) % 4 != 0:
        raise ValueError(f"{bin_path} size is not a multiple of 4 bytes")
    values = struct.unpack(f"<{len(raw) // 2}H", raw)
    return [(values[i], values[i + 1]) for i in range(0, len(values), 2)]


def save_c_file(sequence, c_path, name, name_of):
    """Write a C array for the sequence; name_of(freq) labels each entry."""
    macro = re.sub(r"\W", "_", name).upper()
    array = re.sub(r"\W", "_", name).lower()
    with open(c_path, "w") as f:
        f.write("// Generated by music_creator.py - do not edit manually\n")
        f.write("#include <stdint.h>\n\n")
        f.write(f"#define {macro}_NOTES_NUMBER {len(sequence)}U\n\n")
        f.write(f"const uint16_t {array}_music[{macro}_NOTES_NUMBER * 2U] = {{\n")
        for freq, dur in sequence:
            f.write(f"    {freq}U, {dur}U, // {name_of(freq)}\n")
        f.write("};\n")


def list_bin_names(directory):
    """Base names (no extension) of all .bin files in a directory."""
    if not os.path.isdir(directory):
        return []
    return sorted(
        os.path.splitext(f)[0] for f in os.listdir(directory) if f.endswith(".bin")
    )
