#include "assets.h"
#include "game_console_api.h"
#include "fonts.h"
#include "gamexo_v_bar.h"
#include "gamexo_h_bar.h"
#include "gamexo_corner.h"
#include "gamexo_o.h"
#include "gamexo_x.h"
#include "gamexo_selection.h"

DEFINE_ASSET_HEADER(ASSET_MAGIC, ASSET_VERSION, ASSET_COUNT);

DEFINE_ASSET_8(_asset_font_a, ASSET_ID_FONT_A, ASSET_TYPE_TILE, (DEFINE_FONT_A_TILE));

DEFINE_ASSET_8(_asset_font_b, ASSET_ID_FONT_B, ASSET_TYPE_TILE, (DEFINE_FONT_B_TILE));

DEFINE_ASSET_8(_asset_font_c, ASSET_ID_FONT_C, ASSET_TYPE_TILE, (DEFINE_FONT_C_TILE));

DEFINE_ASSET_8(_asset_font_d, ASSET_ID_FONT_D, ASSET_TYPE_TILE, (DEFINE_FONT_D_TILE));

DEFINE_ASSET_8(_asset_font_e, ASSET_ID_FONT_E, ASSET_TYPE_TILE, (DEFINE_FONT_E_TILE));

DEFINE_ASSET_8(_asset_font_f, ASSET_ID_FONT_F, ASSET_TYPE_TILE, (DEFINE_FONT_F_TILE));

DEFINE_ASSET_8(_asset_font_g, ASSET_ID_FONT_G, ASSET_TYPE_TILE, (DEFINE_FONT_G_TILE));

DEFINE_ASSET_8(_asset_font_h, ASSET_ID_FONT_H, ASSET_TYPE_TILE, (DEFINE_FONT_H_TILE));

DEFINE_ASSET_8(_asset_font_i, ASSET_ID_FONT_I, ASSET_TYPE_TILE, (DEFINE_FONT_I_TILE));

DEFINE_ASSET_8(_asset_font_j, ASSET_ID_FONT_J, ASSET_TYPE_TILE, (DEFINE_FONT_J_TILE));

DEFINE_ASSET_8(_asset_font_k, ASSET_ID_FONT_K, ASSET_TYPE_TILE, (DEFINE_FONT_K_TILE));

DEFINE_ASSET_8(_asset_font_l, ASSET_ID_FONT_L, ASSET_TYPE_TILE, (DEFINE_FONT_L_TILE));

DEFINE_ASSET_8(_asset_font_m, ASSET_ID_FONT_M, ASSET_TYPE_TILE, (DEFINE_FONT_M_TILE));

DEFINE_ASSET_8(_asset_font_n, ASSET_ID_FONT_N, ASSET_TYPE_TILE, (DEFINE_FONT_N_TILE));

DEFINE_ASSET_8(_asset_font_o, ASSET_ID_FONT_O, ASSET_TYPE_TILE, (DEFINE_FONT_O_TILE));

DEFINE_ASSET_8(_asset_font_p, ASSET_ID_FONT_P, ASSET_TYPE_TILE, (DEFINE_FONT_P_TILE));

DEFINE_ASSET_8(_asset_font_q, ASSET_ID_FONT_Q, ASSET_TYPE_TILE, (DEFINE_FONT_Q_TILE));

DEFINE_ASSET_8(_asset_font_r, ASSET_ID_FONT_R, ASSET_TYPE_TILE, (DEFINE_FONT_R_TILE));

DEFINE_ASSET_8(_asset_font_s, ASSET_ID_FONT_S, ASSET_TYPE_TILE, (DEFINE_FONT_S_TILE));

DEFINE_ASSET_8(_asset_font_t, ASSET_ID_FONT_T, ASSET_TYPE_TILE, (DEFINE_FONT_T_TILE));

DEFINE_ASSET_8(_asset_font_u, ASSET_ID_FONT_U, ASSET_TYPE_TILE, (DEFINE_FONT_U_TILE));

DEFINE_ASSET_8(_asset_font_v, ASSET_ID_FONT_V, ASSET_TYPE_TILE, (DEFINE_FONT_V_TILE));

DEFINE_ASSET_8(_asset_font_w, ASSET_ID_FONT_W, ASSET_TYPE_TILE, (DEFINE_FONT_W_TILE));

DEFINE_ASSET_8(_asset_font_x, ASSET_ID_FONT_X, ASSET_TYPE_TILE, (DEFINE_FONT_X_TILE));

DEFINE_ASSET_8(_asset_font_y, ASSET_ID_FONT_Y, ASSET_TYPE_TILE, (DEFINE_FONT_Y_TILE));

DEFINE_ASSET_8(_asset_font_z, ASSET_ID_FONT_Z, ASSET_TYPE_TILE, (DEFINE_FONT_Z_TILE));

DEFINE_ASSET_8(_asset_font_0, ASSET_ID_FONT_0, ASSET_TYPE_TILE, (DEFINE_FONT_0_TILE));

DEFINE_ASSET_8(_asset_font_1, ASSET_ID_FONT_1, ASSET_TYPE_TILE, (DEFINE_FONT_1_TILE));

DEFINE_ASSET_8(_asset_font_2, ASSET_ID_FONT_2, ASSET_TYPE_TILE, (DEFINE_FONT_2_TILE));

DEFINE_ASSET_8(_asset_font_3, ASSET_ID_FONT_3, ASSET_TYPE_TILE, (DEFINE_FONT_3_TILE));

DEFINE_ASSET_8(_asset_font_4, ASSET_ID_FONT_4, ASSET_TYPE_TILE, (DEFINE_FONT_4_TILE));

DEFINE_ASSET_8(_asset_font_5, ASSET_ID_FONT_5, ASSET_TYPE_TILE, (DEFINE_FONT_5_TILE));

DEFINE_ASSET_8(_asset_font_6, ASSET_ID_FONT_6, ASSET_TYPE_TILE, (DEFINE_FONT_6_TILE));

DEFINE_ASSET_8(_asset_font_7, ASSET_ID_FONT_7, ASSET_TYPE_TILE, (DEFINE_FONT_7_TILE));

DEFINE_ASSET_8(_asset_font_8, ASSET_ID_FONT_8, ASSET_TYPE_TILE, (DEFINE_FONT_8_TILE));

DEFINE_ASSET_8(_asset_font_9, ASSET_ID_FONT_9, ASSET_TYPE_TILE, (DEFINE_FONT_9_TILE));

DEFINE_ASSET_8(_asset_font_star, ASSET_ID_FONT_STAR, ASSET_TYPE_TILE, (DEFINE_FONT_STAR_TILE));

DEFINE_ASSET_8(_asset_grid_corner, ASSET_ID_BACKGROUND_CORNER, ASSET_TYPE_TILE, (DEFINE_GAMEXO_CORNER_TILE));

DEFINE_ASSET_8(_asset_grid_v_bar, ASSET_ID_BACKGROUND_V_BAR, ASSET_TYPE_TILE, (DEFINE_GAMEXO_V_BAR_TILE));

DEFINE_ASSET_8(_asset_grid_h_bar, ASSET_ID_BACKGROUND_H_BAR, ASSET_TYPE_TILE, (DEFINE_GAMEXO_H_BAR_TILE));

DEFINE_ASSET_8(_asset_sprite_o, ASSET_ID_SPRITE_O, ASSET_TYPE_TILE, (DEFINE_GAMEXO_O_TILE));

DEFINE_ASSET_8(_asset_sprite_x, ASSET_ID_SPRITE_X, ASSET_TYPE_TILE, (DEFINE_GAMEXO_X_TILE));

DEFINE_ASSET_8(_asset_sprite_selection, ASSET_ID_SPRITE_SELECTION, ASSET_TYPE_TILE, (DEFINE_GAMEXO_SELECTION_TILE));

DEFINE_ASSET_16(_asset_audio_win_sound, ASSET_ID_WIN_SOUND, ASSET_TYPE_AUDIO_DATA, (NOTE_C4, NOTE_E4, NOTE_G4, NOTE_C5, NOTE_E5, NOTE_G5, NOTE_C6));
DEFINE_ASSET_16(_asset_audio_win_duration, ASSET_ID_WIN_SOUND_DURATION, ASSET_TYPE_AUDIO_DURATION, (200, 200, 200, 300, 250, 250, 500));

DEFINE_ASSET_16(_asset_audio_loose_sound, ASSET_ID_LOOSE_SOUND, ASSET_TYPE_AUDIO_DATA, (NOTE_A4, NOTE_G4, NOTE_F4, NOTE_D4, NOTE_PAUSE, NOTE_A3));
DEFINE_ASSET_16(_asset_audio_loose_duration, ASSET_ID_LOOSE_SOUND_DURATION, ASSET_TYPE_AUDIO_DURATION, (300, 300, 300, 600, 100, 800));

DEFINE_ASSET_16(_asset_audio_draw_sound, ASSET_ID_DRAW_SOUND, ASSET_TYPE_AUDIO_DATA, (NOTE_C4, NOTE_G4, NOTE_C4, NOTE_G4, NOTE_C4));
DEFINE_ASSET_16(_asset_audio_draw_duration, ASSET_ID_DRAW_SOUND_DURATION, ASSET_TYPE_AUDIO_DURATION, (250, 250, 250, 250, 500));

DEFINE_ASSET_16(_asset_audio_welcome_sound, ASSET_ID_WELCOME_SOUND, ASSET_TYPE_AUDIO_DATA, (NOTE_C4, NOTE_E4, NOTE_G4, NOTE_E4, NOTE_F4, NOTE_A4, NOTE_C5));
DEFINE_ASSET_16(_asset_audio_welcome_duration, ASSET_ID_WELCOME_SOUND_DURATION, ASSET_TYPE_AUDIO_DURATION, (200, 200, 300, 200, 250, 250, 400));
