// Generated by music_creator.py - do not edit manually
#include "music_track.h"

#define SFX_DRAW_NOTES_NUMBER 2U

const MusicTrackHeader sfx_draw_music_header = {
    .magic = NOTE_ASSET_MAGIC,
    .version = NOTE_ASSET_VERSION,
    .noteCount = SFX_DRAW_NOTES_NUMBER,
    .dataSize = SFX_DRAW_NOTES_NUMBER * sizeof(NoteEntry),
};

const uint16_t sfx_draw_music[SFX_DRAW_NOTES_NUMBER * 2U] = {
    494U, 150U, // 494Hz
    392U, 280U, // 392Hz
};
