// Generated by music_creator.py - do not edit manually
#include "music_track.h"

#define SFX_MOVE_NOTES_NUMBER 1U

const MusicTrackHeader sfx_move_music_header = {
    .magic = NOTE_ASSET_MAGIC,
    .version = NOTE_ASSET_VERSION,
    .noteCount = SFX_MOVE_NOTES_NUMBER,
    .dataSize = SFX_MOVE_NOTES_NUMBER * sizeof(NoteEntry),
};

const uint16_t sfx_move_music[SFX_MOVE_NOTES_NUMBER * 2U] = {
    659U, 40U, // 659Hz
};
