// Generated by pixel_forge.py - do not edit manually
#include "gfx_asset.h"

#define FONT5X5_034_WIDTH 5U
#define FONT5X5_034_HEIGHT 5U
#define FONT5X5_034_DATA_SIZE 10U

const GfxAssetHeader font5x5_034_gfx_header = {
    .magic = GFX_ASSET_MAGIC,
    .width = FONT5X5_034_WIDTH,
    .height = FONT5X5_034_HEIGHT,
    .format = GFX_FMT_2BPP,
    .dataSize = FONT5X5_034_DATA_SIZE,
    .flags = 0,
};

// system palette indices (slot 0 is transparent, its color is the backdrop)
const uint8_t font5x5_034_gfx_palette[GFX_PALETTE_COLORS_2BPP] = {
    0x0D, 0x0D, 0x0D, 0x0D,
};

// pixels: 2bpp, 2 byte(s) per row
const uint8_t font5x5_034_gfx_data[FONT5X5_034_DATA_SIZE] = {
    0x11, 0x00, // row 0
    0x11, 0x00, // row 1
    0x00, 0x00, // row 2
    0x00, 0x00, // row 3
    0x00, 0x00, // row 4
};
