// Generated by pixel_forge.py - do not edit manually
#include "gfx_asset.h"

#define FONT3X5_107_WIDTH 3U
#define FONT3X5_107_HEIGHT 5U
#define FONT3X5_107_DATA_SIZE 5U

const GfxAssetHeader font3x5_107_gfx_header = {
    .magic = GFX_ASSET_MAGIC,
    .width = FONT3X5_107_WIDTH,
    .height = FONT3X5_107_HEIGHT,
    .format = GFX_FMT_2BPP,
    .dataSize = FONT3X5_107_DATA_SIZE,
    .flags = 0,
};

// system palette indices (slot 0 is transparent, its color is the backdrop)
const uint8_t font3x5_107_gfx_palette[GFX_PALETTE_COLORS_2BPP] = {
    0x0D, 0x0D, 0x0D, 0x0D,
};

// pixels: 2bpp, 1 byte(s) per row
const uint8_t font3x5_107_gfx_data[FONT3X5_107_DATA_SIZE] = {
    0x40, // row 0
    0x44, // row 1
    0x50, // row 2
    0x44, // row 3
    0x00, // row 4
};
