// Generated by tools/graphics/generate_fonts.py
#ifndef __FONT3X5_H
#define __FONT3X5_H

#include "font_interface.h"

#define FONT3X5_GLYPH_W 3U
#define FONT3X5_GLYPH_H 5U
#define FONT3X5_GLYPH_STRIDE 1U
#define FONT3X5_FONT_SIZE FONT_3x5

extern const Font font3x5;

#endif /* __FONT3X5_H */
