// Generated by tools/graphics/generate_fonts.py
#ifndef __FONT_TYPES_H
#define __FONT_TYPES_H

#include <stdint.h>

#define FONT_TABLE_LEN 95U  // 0x20-0x7E

/** Which built-in console font size. */
typedef enum {
    FONT_3x5 = 0,
    FONT_5x5 = 1,
    FONT_8x8 = 2,
} FontSize;

/** One glyph in the font. .pixels drops straight into a Sprite. */
typedef struct {
    const uint8_t *pixels;
} FontGlyph;

/** Full printable-ASCII font, indexed glyphs[codepoint - 0x20]. */
typedef struct {
    const FontGlyph glyphs[FONT_TABLE_LEN];
    const uint16_t palette[4];
    uint8_t glyph_w, glyph_h;
    FontSize  size;
} Font;

#endif /* __FONT_TYPES_H */
