// Convenience header: every built-in console font.
// Generated by tools/graphics/generate_fonts.py — rerun the script to refresh
// the data arrays.
#ifndef __FONTS_H
#define __FONTS_H

#include "font_interface.h"
#include "Fonts/font3x5.h"
#include "Fonts/font5x5.h"
#include "Fonts/font8x8.h"

#endif /* __FONTS_H */
