// Generated by tools/graphics/generate_fonts.py
#ifndef __FONT8X8_H
#define __FONT8X8_H

#include "font_types.h"

#define FONT8X8_GLYPH_W 8U
#define FONT8X8_GLYPH_H 8U
#define FONT8X8_GLYPH_STRIDE 2U
#define FONT8X8_FONT_SIZE FONT_8x8

extern const Font font8x8;

#endif /* __FONT8X8_H */
