// Generated by tools/graphics/generate_fonts.py
#ifndef __FONT5X5_H
#define __FONT5X5_H

#include "font_types.h"

#define FONT5X5_GLYPH_W 5U
#define FONT5X5_GLYPH_H 5U
#define FONT5X5_GLYPH_STRIDE 2U
#define FONT5X5_FONT_SIZE FONT_5x5

extern const Font font5x5;

#endif /* __FONT5X5_H */
