// Generated by tools/graphics/generate_fonts.py
#include "font3x5.h"

// Packed 2bpp glyph data (4 px/byte, MSB-first row-major)
static const uint8_t _font3x5_glyph_data_033[5U] = {
        0x10,
        0x10,
        0x00,
        0x10,
        0x00,
};
static const uint8_t _font3x5_glyph_data_034[5U] = {
        0x44,
        0x44,
        0x00,
        0x00,
        0x00,
};
static const uint8_t _font3x5_glyph_data_035[5U] = {
        0x44,
        0x54,
        0x44,
        0x54,
        0x00,
};
static const uint8_t _font3x5_glyph_data_036[5U] = {
        0x54,
        0x50,
        0x54,
        0x14,
        0x54,
};
static const uint8_t _font3x5_glyph_data_037[5U] = {
        0x44,
        0x04,
        0x50,
        0x44,
        0x00,
};
static const uint8_t _font3x5_glyph_data_038[5U] = {
        0x10,
        0x44,
        0x44,
        0x00,
        0x00,
};
static const uint8_t _font3x5_glyph_data_039[5U] = {
        0x10,
        0x10,
        0x00,
        0x00,
        0x00,
};
static const uint8_t _font3x5_glyph_data_040[5U] = {
        0x04,
        0x10,
        0x10,
        0x04,
        0x00,
};
static const uint8_t _font3x5_glyph_data_041[5U] = {
        0x10,
        0x04,
        0x04,
        0x10,
        0x00,
};
static const uint8_t _font3x5_glyph_data_042[5U] = {
        0x44,
        0x10,
        0x44,
        0x00,
        0x00,
};
static const uint8_t _font3x5_glyph_data_043[5U] = {
        0x10,
        0x54,
        0x10,
        0x00,
        0x00,
};
static const uint8_t _font3x5_glyph_data_044[5U] = {
        0x00,
        0x00,
        0x00,
        0x04,
        0x14,
};
static const uint8_t _font3x5_glyph_data_045[5U] = {
        0x00,
        0x54,
        0x00,
        0x00,
        0x00,
};
static const uint8_t _font3x5_glyph_data_046[5U] = {
        0x00,
        0x00,
        0x00,
        0x10,
        0x00,
};
static const uint8_t _font3x5_glyph_data_047[5U] = {
        0x04,
        0x10,
        0x10,
        0x40,
        0x00,
};
static const uint8_t _font3x5_glyph_data_048[5U] = {
        0x54,
        0x44,
        0x44,
        0x54,
        0x00,
};
static const uint8_t _font3x5_glyph_data_049[5U] = {
        0x14,
        0x04,
        0x04,
        0x04,
        0x00,
};
static const uint8_t _font3x5_glyph_data_050[5U] = {
        0x54,
        0x04,
        0x50,
        0x54,
        0x00,
};
static const uint8_t _font3x5_glyph_data_051[5U] = {
        0x54,
        0x14,
        0x04,
        0x54,
        0x00,
};
static const uint8_t _font3x5_glyph_data_052[5U] = {
        0x44,
        0x44,
        0x54,
        0x04,
        0x00,
};
static const uint8_t _font3x5_glyph_data_053[5U] = {
        0x54,
        0x50,
        0x04,
        0x54,
        0x00,
};
static const uint8_t _font3x5_glyph_data_054[5U] = {
        0x54,
        0x40,
        0x54,
        0x54,
        0x00,
};
static const uint8_t _font3x5_glyph_data_055[5U] = {
        0x54,
        0x04,
        0x14,
        0x04,
        0x00,
};
static const uint8_t _font3x5_glyph_data_056[5U] = {
        0x54,
        0x54,
        0x44,
        0x54,
        0x00,
};
static const uint8_t _font3x5_glyph_data_057[5U] = {
        0x54,
        0x54,
        0x04,
        0x54,
        0x00,
};
static const uint8_t _font3x5_glyph_data_058[5U] = {
        0x00,
        0x10,
        0x00,
        0x10,
        0x00,
};
static const uint8_t _font3x5_glyph_data_059[5U] = {
        0x00,
        0x10,
        0x00,
        0x10,
        0x50,
};
static const uint8_t _font3x5_glyph_data_060[5U] = {
        0x04,
        0x10,
        0x40,
        0x10,
        0x04,
};
static const uint8_t _font3x5_glyph_data_061[5U] = {
        0x54,
        0x00,
        0x54,
        0x00,
        0x00,
};
static const uint8_t _font3x5_glyph_data_062[5U] = {
        0x40,
        0x10,
        0x04,
        0x10,
        0x40,
};
static const uint8_t _font3x5_glyph_data_063[5U] = {
        0x54,
        0x04,
        0x00,
        0x10,
        0x00,
};
static const uint8_t _font3x5_glyph_data_064[5U] = {
        0x54,
        0x44,
        0x54,
        0x40,
        0x00,
};
static const uint8_t _font3x5_glyph_data_065[5U] = {
        0x54,
        0x44,
        0x54,
        0x44,
        0x00,
};
static const uint8_t _font3x5_glyph_data_066[5U] = {
        0x50,
        0x54,
        0x44,
        0x54,
        0x00,
};
static const uint8_t _font3x5_glyph_data_067[5U] = {
        0x54,
        0x40,
        0x40,
        0x54,
        0x00,
};
static const uint8_t _font3x5_glyph_data_068[5U] = {
        0x50,
        0x44,
        0x44,
        0x50,
        0x00,
};
static const uint8_t _font3x5_glyph_data_069[5U] = {
        0x54,
        0x50,
        0x40,
        0x54,
        0x00,
};
static const uint8_t _font3x5_glyph_data_070[5U] = {
        0x54,
        0x40,
        0x50,
        0x40,
        0x00,
};
static const uint8_t _font3x5_glyph_data_071[5U] = {
        0x54,
        0x40,
        0x44,
        0x54,
        0x00,
};
static const uint8_t _font3x5_glyph_data_072[5U] = {
        0x44,
        0x54,
        0x44,
        0x44,
        0x00,
};
static const uint8_t _font3x5_glyph_data_073[5U] = {
        0x54,
        0x10,
        0x10,
        0x54,
        0x00,
};
static const uint8_t _font3x5_glyph_data_074[5U] = {
        0x54,
        0x10,
        0x10,
        0x50,
        0x00,
};
static const uint8_t _font3x5_glyph_data_075[5U] = {
        0x44,
        0x50,
        0x50,
        0x44,
        0x00,
};
static const uint8_t _font3x5_glyph_data_076[5U] = {
        0x40,
        0x40,
        0x40,
        0x54,
        0x00,
};
static const uint8_t _font3x5_glyph_data_077[5U] = {
        0x54,
        0x54,
        0x54,
        0x44,
        0x00,
};
static const uint8_t _font3x5_glyph_data_078[5U] = {
        0x54,
        0x44,
        0x44,
        0x44,
        0x00,
};
static const uint8_t _font3x5_glyph_data_079[5U] = {
        0x54,
        0x44,
        0x44,
        0x54,
        0x00,
};
static const uint8_t _font3x5_glyph_data_080[5U] = {
        0x54,
        0x44,
        0x54,
        0x40,
        0x00,
};
static const uint8_t _font3x5_glyph_data_081[5U] = {
        0x54,
        0x44,
        0x54,
        0x04,
        0x00,
};
static const uint8_t _font3x5_glyph_data_082[5U] = {
        0x54,
        0x54,
        0x50,
        0x44,
        0x00,
};
static const uint8_t _font3x5_glyph_data_083[5U] = {
        0x54,
        0x40,
        0x14,
        0x54,
        0x00,
};
static const uint8_t _font3x5_glyph_data_084[5U] = {
        0x54,
        0x10,
        0x10,
        0x10,
        0x00,
};
static const uint8_t _font3x5_glyph_data_085[5U] = {
        0x44,
        0x44,
        0x44,
        0x54,
        0x00,
};
static const uint8_t _font3x5_glyph_data_086[5U] = {
        0x44,
        0x44,
        0x44,
        0x10,
        0x00,
};
static const uint8_t _font3x5_glyph_data_087[5U] = {
        0x44,
        0x54,
        0x54,
        0x54,
        0x00,
};
static const uint8_t _font3x5_glyph_data_088[5U] = {
        0x44,
        0x50,
        0x14,
        0x44,
        0x00,
};
static const uint8_t _font3x5_glyph_data_089[5U] = {
        0x44,
        0x54,
        0x10,
        0x10,
        0x00,
};
static const uint8_t _font3x5_glyph_data_090[5U] = {
        0x54,
        0x14,
        0x40,
        0x54,
        0x00,
};
static const uint8_t _font3x5_glyph_data_091[5U] = {
        0x50,
        0x40,
        0x40,
        0x40,
        0x50,
};
static const uint8_t _font3x5_glyph_data_092[5U] = {
        0x40,
        0x40,
        0x10,
        0x04,
        0x04,
};
static const uint8_t _font3x5_glyph_data_093[5U] = {
        0x14,
        0x04,
        0x04,
        0x04,
        0x14,
};
static const uint8_t _font3x5_glyph_data_094[5U] = {
        0x10,
        0x44,
        0x00,
        0x00,
        0x00,
};
static const uint8_t _font3x5_glyph_data_095[5U] = {
        0x00,
        0x00,
        0x00,
        0x00,
        0x54,
};
static const uint8_t _font3x5_glyph_data_096[5U] = {
        0x40,
        0x10,
        0x00,
        0x00,
        0x00,
};
static const uint8_t _font3x5_glyph_data_097[5U] = {
        0x00,
        0x14,
        0x54,
        0x54,
        0x00,
};
static const uint8_t _font3x5_glyph_data_098[5U] = {
        0x40,
        0x54,
        0x44,
        0x54,
        0x00,
};
static const uint8_t _font3x5_glyph_data_099[5U] = {
        0x00,
        0x54,
        0x40,
        0x54,
        0x00,
};
static const uint8_t _font3x5_glyph_data_100[5U] = {
        0x04,
        0x54,
        0x44,
        0x54,
        0x00,
};
static const uint8_t _font3x5_glyph_data_101[5U] = {
        0x00,
        0x50,
        0x50,
        0x54,
        0x00,
};
static const uint8_t _font3x5_glyph_data_102[5U] = {
        0x14,
        0x10,
        0x54,
        0x10,
        0x00,
};
static const uint8_t _font3x5_glyph_data_103[5U] = {
        0x00,
        0x54,
        0x54,
        0x04,
        0x54,
};
static const uint8_t _font3x5_glyph_data_104[5U] = {
        0x40,
        0x54,
        0x44,
        0x44,
        0x00,
};
static const uint8_t _font3x5_glyph_data_105[5U] = {
        0x10,
        0x00,
        0x10,
        0x10,
        0x00,
};
static const uint8_t _font3x5_glyph_data_106[5U] = {
        0x04,
        0x00,
        0x04,
        0x04,
        0x14,
};
static const uint8_t _font3x5_glyph_data_107[5U] = {
        0x40,
        0x44,
        0x50,
        0x44,
        0x00,
};
static const uint8_t _font3x5_glyph_data_108[5U] = {
        0x10,
        0x10,
        0x10,
        0x14,
        0x00,
};
static const uint8_t _font3x5_glyph_data_109[5U] = {
        0x00,
        0x54,
        0x54,
        0x44,
        0x00,
};
static const uint8_t _font3x5_glyph_data_110[5U] = {
        0x00,
        0x54,
        0x44,
        0x44,
        0x00,
};
static const uint8_t _font3x5_glyph_data_111[5U] = {
        0x00,
        0x54,
        0x44,
        0x54,
        0x00,
};
static const uint8_t _font3x5_glyph_data_112[5U] = {
        0x00,
        0x54,
        0x44,
        0x54,
        0x40,
};
static const uint8_t _font3x5_glyph_data_113[5U] = {
        0x00,
        0x54,
        0x44,
        0x54,
        0x04,
};
static const uint8_t _font3x5_glyph_data_114[5U] = {
        0x00,
        0x54,
        0x40,
        0x40,
        0x00,
};
static const uint8_t _font3x5_glyph_data_115[5U] = {
        0x00,
        0x14,
        0x10,
        0x50,
        0x00,
};
static const uint8_t _font3x5_glyph_data_116[5U] = {
        0x10,
        0x54,
        0x10,
        0x14,
        0x00,
};
static const uint8_t _font3x5_glyph_data_117[5U] = {
        0x00,
        0x44,
        0x44,
        0x54,
        0x00,
};
static const uint8_t _font3x5_glyph_data_118[5U] = {
        0x00,
        0x44,
        0x44,
        0x10,
        0x00,
};
static const uint8_t _font3x5_glyph_data_119[5U] = {
        0x00,
        0x44,
        0x54,
        0x54,
        0x00,
};
static const uint8_t _font3x5_glyph_data_120[5U] = {
        0x00,
        0x44,
        0x10,
        0x44,
        0x00,
};
static const uint8_t _font3x5_glyph_data_121[5U] = {
        0x00,
        0x44,
        0x54,
        0x04,
        0x50,
};
static const uint8_t _font3x5_glyph_data_122[5U] = {
        0x00,
        0x54,
        0x10,
        0x04,
        0x50,
};
static const uint8_t _font3x5_glyph_data_123[5U] = {
        0x04,
        0x10,
        0x50,
        0x10,
        0x04,
};
static const uint8_t _font3x5_glyph_data_124[5U] = {
        0x10,
        0x10,
        0x10,
        0x10,
        0x10,
};
static const uint8_t _font3x5_glyph_data_125[5U] = {
        0x40,
        0x10,
        0x14,
        0x10,
        0x40,
};
static const uint8_t _font3x5_glyph_data_126[5U] = {
        0x00,
        0x50,
        0x14,
        0x00,
        0x00,
};

// shared blank glyph (5 zero bytes)
static const uint8_t _font3x5_glyph_blank[5U] = {0};

const Font font3x5 = {
    .glyphs = {
        [  0U] = {.pixels = _font3x5_glyph_blank}, // 0x20
        [  1U] = {.pixels = _font3x5_glyph_data_033}, // 0x21 !
        [  2U] = {.pixels = _font3x5_glyph_data_034}, // 0x22
        [  3U] = {.pixels = _font3x5_glyph_data_035}, // 0x23 #
        [  4U] = {.pixels = _font3x5_glyph_data_036}, // 0x24 $
        [  5U] = {.pixels = _font3x5_glyph_data_037}, // 0x25 %
        [  6U] = {.pixels = _font3x5_glyph_data_038}, // 0x26 &
        [  7U] = {.pixels = _font3x5_glyph_data_039}, // 0x27 '
        [  8U] = {.pixels = _font3x5_glyph_data_040}, // 0x28 (
        [  9U] = {.pixels = _font3x5_glyph_data_041}, // 0x29 )
        [ 10U] = {.pixels = _font3x5_glyph_data_042}, // 0x2A *
        [ 11U] = {.pixels = _font3x5_glyph_data_043}, // 0x2B +
        [ 12U] = {.pixels = _font3x5_glyph_data_044}, // 0x2C ,
        [ 13U] = {.pixels = _font3x5_glyph_data_045}, // 0x2D -
        [ 14U] = {.pixels = _font3x5_glyph_data_046}, // 0x2E .
        [ 15U] = {.pixels = _font3x5_glyph_data_047}, // 0x2F /
        [ 16U] = {.pixels = _font3x5_glyph_data_048}, // 0x30 0
        [ 17U] = {.pixels = _font3x5_glyph_data_049}, // 0x31 1
        [ 18U] = {.pixels = _font3x5_glyph_data_050}, // 0x32 2
        [ 19U] = {.pixels = _font3x5_glyph_data_051}, // 0x33 3
        [ 20U] = {.pixels = _font3x5_glyph_data_052}, // 0x34 4
        [ 21U] = {.pixels = _font3x5_glyph_data_053}, // 0x35 5
        [ 22U] = {.pixels = _font3x5_glyph_data_054}, // 0x36 6
        [ 23U] = {.pixels = _font3x5_glyph_data_055}, // 0x37 7
        [ 24U] = {.pixels = _font3x5_glyph_data_056}, // 0x38 8
        [ 25U] = {.pixels = _font3x5_glyph_data_057}, // 0x39 9
        [ 26U] = {.pixels = _font3x5_glyph_data_058}, // 0x3A :
        [ 27U] = {.pixels = _font3x5_glyph_data_059}, // 0x3B ;
        [ 28U] = {.pixels = _font3x5_glyph_data_060}, // 0x3C <
        [ 29U] = {.pixels = _font3x5_glyph_data_061}, // 0x3D =
        [ 30U] = {.pixels = _font3x5_glyph_data_062}, // 0x3E >
        [ 31U] = {.pixels = _font3x5_glyph_data_063}, // 0x3F ?
        [ 32U] = {.pixels = _font3x5_glyph_data_064}, // 0x40 @
        [ 33U] = {.pixels = _font3x5_glyph_data_065}, // 0x41 A
        [ 34U] = {.pixels = _font3x5_glyph_data_066}, // 0x42 B
        [ 35U] = {.pixels = _font3x5_glyph_data_067}, // 0x43 C
        [ 36U] = {.pixels = _font3x5_glyph_data_068}, // 0x44 D
        [ 37U] = {.pixels = _font3x5_glyph_data_069}, // 0x45 E
        [ 38U] = {.pixels = _font3x5_glyph_data_070}, // 0x46 F
        [ 39U] = {.pixels = _font3x5_glyph_data_071}, // 0x47 G
        [ 40U] = {.pixels = _font3x5_glyph_data_072}, // 0x48 H
        [ 41U] = {.pixels = _font3x5_glyph_data_073}, // 0x49 I
        [ 42U] = {.pixels = _font3x5_glyph_data_074}, // 0x4A J
        [ 43U] = {.pixels = _font3x5_glyph_data_075}, // 0x4B K
        [ 44U] = {.pixels = _font3x5_glyph_data_076}, // 0x4C L
        [ 45U] = {.pixels = _font3x5_glyph_data_077}, // 0x4D M
        [ 46U] = {.pixels = _font3x5_glyph_data_078}, // 0x4E N
        [ 47U] = {.pixels = _font3x5_glyph_data_079}, // 0x4F O
        [ 48U] = {.pixels = _font3x5_glyph_data_080}, // 0x50 P
        [ 49U] = {.pixels = _font3x5_glyph_data_081}, // 0x51 Q
        [ 50U] = {.pixels = _font3x5_glyph_data_082}, // 0x52 R
        [ 51U] = {.pixels = _font3x5_glyph_data_083}, // 0x53 S
        [ 52U] = {.pixels = _font3x5_glyph_data_084}, // 0x54 T
        [ 53U] = {.pixels = _font3x5_glyph_data_085}, // 0x55 U
        [ 54U] = {.pixels = _font3x5_glyph_data_086}, // 0x56 V
        [ 55U] = {.pixels = _font3x5_glyph_data_087}, // 0x57 W
        [ 56U] = {.pixels = _font3x5_glyph_data_088}, // 0x58 X
        [ 57U] = {.pixels = _font3x5_glyph_data_089}, // 0x59 Y
        [ 58U] = {.pixels = _font3x5_glyph_data_090}, // 0x5A Z
        [ 59U] = {.pixels = _font3x5_glyph_data_091}, // 0x5B [
        [ 60U] = {.pixels = _font3x5_glyph_data_092}, // 0x5C
        [ 61U] = {.pixels = _font3x5_glyph_data_093}, // 0x5D ]
        [ 62U] = {.pixels = _font3x5_glyph_data_094}, // 0x5E ^
        [ 63U] = {.pixels = _font3x5_glyph_data_095}, // 0x5F _
        [ 64U] = {.pixels = _font3x5_glyph_data_096}, // 0x60 `
        [ 65U] = {.pixels = _font3x5_glyph_data_097}, // 0x61 a
        [ 66U] = {.pixels = _font3x5_glyph_data_098}, // 0x62 b
        [ 67U] = {.pixels = _font3x5_glyph_data_099}, // 0x63 c
        [ 68U] = {.pixels = _font3x5_glyph_data_100}, // 0x64 d
        [ 69U] = {.pixels = _font3x5_glyph_data_101}, // 0x65 e
        [ 70U] = {.pixels = _font3x5_glyph_data_102}, // 0x66 f
        [ 71U] = {.pixels = _font3x5_glyph_data_103}, // 0x67 g
        [ 72U] = {.pixels = _font3x5_glyph_data_104}, // 0x68 h
        [ 73U] = {.pixels = _font3x5_glyph_data_105}, // 0x69 i
        [ 74U] = {.pixels = _font3x5_glyph_data_106}, // 0x6A j
        [ 75U] = {.pixels = _font3x5_glyph_data_107}, // 0x6B k
        [ 76U] = {.pixels = _font3x5_glyph_data_108}, // 0x6C l
        [ 77U] = {.pixels = _font3x5_glyph_data_109}, // 0x6D m
        [ 78U] = {.pixels = _font3x5_glyph_data_110}, // 0x6E n
        [ 79U] = {.pixels = _font3x5_glyph_data_111}, // 0x6F o
        [ 80U] = {.pixels = _font3x5_glyph_data_112}, // 0x70 p
        [ 81U] = {.pixels = _font3x5_glyph_data_113}, // 0x71 q
        [ 82U] = {.pixels = _font3x5_glyph_data_114}, // 0x72 r
        [ 83U] = {.pixels = _font3x5_glyph_data_115}, // 0x73 s
        [ 84U] = {.pixels = _font3x5_glyph_data_116}, // 0x74 t
        [ 85U] = {.pixels = _font3x5_glyph_data_117}, // 0x75 u
        [ 86U] = {.pixels = _font3x5_glyph_data_118}, // 0x76 v
        [ 87U] = {.pixels = _font3x5_glyph_data_119}, // 0x77 w
        [ 88U] = {.pixels = _font3x5_glyph_data_120}, // 0x78 x
        [ 89U] = {.pixels = _font3x5_glyph_data_121}, // 0x79 y
        [ 90U] = {.pixels = _font3x5_glyph_data_122}, // 0x7A z
        [ 91U] = {.pixels = _font3x5_glyph_data_123}, // 0x7B {
        [ 92U] = {.pixels = _font3x5_glyph_data_124}, // 0x7C |
        [ 93U] = {.pixels = _font3x5_glyph_data_125}, // 0x7D }
        [ 94U] = {.pixels = _font3x5_glyph_data_126}, // 0x7E ~
    },
    .palette = {
        0x0000U, 0xFFFFU, 0xFFFFU, 0xFFFFU,
    },
    .glyph_w = FONT3X5_GLYPH_W,
    .glyph_h = FONT3X5_GLYPH_H,
    .size    = FONT_3x5,
};
