// Generated by music_creator.py - do not edit manually
#include "music_track.h"

#define SFX_WIN_NOTES_NUMBER 4U

const MusicTrackHeader sfx_win_music_header = {
    .magic = NOTE_ASSET_MAGIC,
    .version = NOTE_ASSET_VERSION,
    .noteCount = SFX_WIN_NOTES_NUMBER,
    .dataSize = SFX_WIN_NOTES_NUMBER * sizeof(NoteEntry),
};

const uint16_t sfx_win_music[SFX_WIN_NOTES_NUMBER * 2U] = {
    523U, 120U, // 523Hz
    659U, 120U, // 659Hz
    784U, 120U, // 784Hz
    1047U, 280U, // 1047Hz
};
