// Generated by music_creator.py - do not edit manually
#include "music_track.h"

#define SFX_LOSE_NOTES_NUMBER 3U

const MusicTrackHeader sfx_lose_music_header = {
    .magic = NOTE_ASSET_MAGIC,
    .version = NOTE_ASSET_VERSION,
    .noteCount = SFX_LOSE_NOTES_NUMBER,
    .dataSize = SFX_LOSE_NOTES_NUMBER * sizeof(NoteEntry),
};

const uint16_t sfx_lose_music[SFX_LOSE_NOTES_NUMBER * 2U] = {
    440U, 160U, // 440Hz
    349U, 160U, // 349Hz
    262U, 320U, // 262Hz
};
