// Generated by music_creator.py - do not edit manually
#include "music_track.h"

#define SFX_INTRO_NOTES_NUMBER 4U

const MusicTrackHeader sfx_intro_music_header = {
    .magic = NOTE_ASSET_MAGIC,
    .version = NOTE_ASSET_VERSION,
    .noteCount = SFX_INTRO_NOTES_NUMBER,
    .dataSize = SFX_INTRO_NOTES_NUMBER * sizeof(NoteEntry),
};

const uint16_t sfx_intro_music[SFX_INTRO_NOTES_NUMBER * 2U] = {
    392U, 120U, // 392Hz
    523U, 120U, // 523Hz
    659U, 120U, // 659Hz
    784U, 220U, // 784Hz
};
