// Generated by pixel_forge.py - do not edit manually
#include "gfx_asset.h"

#define FONT8X8_104_WIDTH 8U
#define FONT8X8_104_HEIGHT 8U
#define FONT8X8_104_DATA_SIZE 16U

const GfxAssetHeader font8x8_104_gfx_header = {
    .magic = GFX_ASSET_MAGIC,
    .width = FONT8X8_104_WIDTH,
    .height = FONT8X8_104_HEIGHT,
    .format = GFX_FMT_2BPP,
    .dataSize = FONT8X8_104_DATA_SIZE,
    .flags = 0,
};

// system palette indices (slot 0 is transparent, its color is the backdrop)
const uint8_t font8x8_104_gfx_palette[GFX_PALETTE_COLORS_2BPP] = {
    0x0D, 0x0D, 0x0D, 0x0D,
};

// pixels: 2bpp, 2 byte(s) per row
const uint8_t font8x8_104_gfx_data[FONT8X8_104_DATA_SIZE] = {
    0x10, 0x00, // row 0
    0x10, 0x00, // row 1
    0x15, 0x50, // row 2
    0x10, 0x04, // row 3
    0x10, 0x04, // row 4
    0x10, 0x04, // row 5
    0x10, 0x04, // row 6
    0x00, 0x00, // row 7
};
