"""Generating the C asset-id enum header included by games."""

from __future__ import annotations

import re

from .manifest import Manifest


def render_enum_header(manifest: Manifest, output_name: str) -> str:
    """Render the ``<output_name>AssetEnum.h`` text for a manifest.

    The enum type is named ``<output_name>AssetId`` so several generated headers
    can be included in the same translation unit without colliding.
    """
    ident = _c_identifier(output_name)
    guard = f"{ident.upper()}_ASSET_ENUM_H"
    lines = [
        "// Generated by packer.py from the asset manifest - do not edit manually.",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        "typedef enum {",
    ]
    lines += [f"    {spec.name} = {spec.id}," for spec in manifest.assets]
    lines += [f"}} {ident}AssetId;", "", f"#endif // {guard}", ""]
    return "\n".join(lines)


def _c_identifier(text: str) -> str:
    """Turn an arbitrary output name into a safe C identifier (for the guard)."""
    cleaned = re.sub(r"\W", "_", text)
    if not cleaned or cleaned[0].isdigit():
        cleaned = "_" + cleaned
    return cleaned
