// Generated by music_creator.py - do not edit manually
#include "music_track.h"

#define BACKGROUND_NOTES_NUMBER 87U

const MusicTrackHeader background_music_header = {
    .magic = NOTE_ASSET_MAGIC,
    .version = NOTE_ASSET_VERSION,
    .noteCount = BACKGROUND_NOTES_NUMBER,
    .dataSize = BACKGROUND_NOTES_NUMBER * sizeof(NoteEntry),
};

const uint16_t background_music[BACKGROUND_NOTES_NUMBER * 2U] = {
    440U, 200U, // A4
    523U, 200U, // C5
    659U, 200U, // E5
    523U, 200U, // C5
    880U, 400U, // A5
    659U, 200U, // E5
    0U, 200U, // PAUSE
    391U, 200U, // G4
    493U, 200U, // B4
    587U, 200U, // D5
    493U, 200U, // B4
    783U, 400U, // G5
    587U, 200U, // D5
    0U, 200U, // PAUSE
    349U, 200U, // F4
    440U, 200U, // A4
    523U, 200U, // C5
    440U, 200U, // A4
    698U, 400U, // F5
    523U, 200U, // C5
    0U, 200U, // PAUSE
    329U, 200U, // E4
    415U, 200U, // GS4
    493U, 200U, // B4
    415U, 200U, // GS4
    659U, 400U, // E5
    493U, 200U, // B4
    0U, 200U, // PAUSE
    440U, 200U, // A4
    523U, 200U, // C5
    659U, 200U, // E5
    523U, 200U, // C5
    880U, 400U, // A5
    659U, 200U, // E5
    0U, 200U, // PAUSE
    391U, 200U, // G4
    493U, 200U, // B4
    587U, 200U, // D5
    493U, 200U, // B4
    783U, 400U, // G5
    587U, 200U, // D5
    0U, 200U, // PAUSE
    349U, 200U, // F4
    440U, 200U, // A4
    523U, 200U, // C5
    440U, 200U, // A4
    698U, 400U, // F5
    523U, 200U, // C5
    0U, 200U, // PAUSE
    329U, 200U, // E4
    415U, 200U, // GS4
    493U, 200U, // B4
    415U, 200U, // GS4
    659U, 400U, // E5
    493U, 200U, // B4
    0U, 200U, // PAUSE
    880U, 400U, // A5
    783U, 200U, // G5
    659U, 400U, // E5
    587U, 200U, // D5
    523U, 400U, // C5
    0U, 200U, // PAUSE
    587U, 400U, // D5
    659U, 200U, // E5
    587U, 400U, // D5
    493U, 200U, // B4
    391U, 400U, // G4
    0U, 200U, // PAUSE
    698U, 400U, // F5
    659U, 200U, // E5
    587U, 400U, // D5
    523U, 200U, // C5
    440U, 400U, // A4
    0U, 200U, // PAUSE
    493U, 200U, // B4
    523U, 200U, // C5
    587U, 200U, // D5
    659U, 800U, // E5
    0U, 400U, // PAUSE
    440U, 200U, // A4
    523U, 200U, // C5
    659U, 200U, // E5
    523U, 200U, // C5
    493U, 400U, // B4
    415U, 400U, // GS4
    329U, 800U, // E4
    0U, 400U, // PAUSE
};
