// Generated by music_creator.py - do not edit manually
#include "music_track.h"

#define EXPLOSION_NOTES_NUMBER 27U

const MusicTrackHeader explosion_music_header = {
    .magic = NOTE_ASSET_MAGIC,
    .version = NOTE_ASSET_VERSION,
    .noteCount = EXPLOSION_NOTES_NUMBER,
    .dataSize = EXPLOSION_NOTES_NUMBER * sizeof(NoteEntry),
};

const uint16_t explosion_music[EXPLOSION_NOTES_NUMBER * 2U] = {
    1865U, 12U, // AS6
    1397U, 12U, // F6
    932U, 14U, // AS5
    329U, 16U, // E4
    277U, 22U, // CS4
    261U, 18U, // C4
    220U, 24U, // A3
    207U, 20U, // GS3
    174U, 16U, // F3
    164U, 22U, // E3
    138U, 18U, // CS3
    130U, 24U, // C3
    110U, 20U, // A2
    104U, 16U, // GS2
    87U, 22U, // F2
    82U, 18U, // E2
    69U, 24U, // CS2
    65U, 20U, // C2
    0U, 30U, // PAUSE
    41U, 45U, // E1
    0U, 55U, // PAUSE
    35U, 50U, // CS1
    0U, 85U, // PAUSE
    33U, 60U, // C1
    0U, 125U, // PAUSE
    33U, 40U, // C1
    0U, 60U, // PAUSE
};
